### PR TITLE
Develop mensural

### PR DESCRIPTION
**Pull request by donbyrd**
This is my first pull request ever, so I hope I'm not doing anything stupid! But I've been working in the develop-mensural branch of the CHMTL repository: not good, since we agreed we'd use develop-mensural for synchronization. So I just created a new branch in the CHMTL repository, develop-chmtl (actually, I had a branch by that name, but it was just an old version of develop-mensural, so I deleted it first), so now I think I'm ready to get your recent updates to rism-ch's develop-mensural, Laurent. Now what? There are a bunch of conflicts. How about I try to resolve them before bothering you?

### CODE REVIEW

**Comment by lpugin** [comment]
There is obviously a problem since its says that more than 500 files where modified. This should not be the case because I assume you modified only a couple of files. So yes please try to sort this out and make a new pull request

**Comment by donbyrd** [comment]
Most of the 535 changed files are XML files for Bravura, Gootville, and Leipizig; I never touched any of those. There are also quite a few .h and .cpp files, but the vast majority of those are also files I never touched. But I don't think that's a problem; GitHub lists only seven files that have conflicts, and, offhand, I could believe those are exactly the files I've modified. So I don't see any evidence there's anything wrong with my pull request! How about I reopen it and try to resolve the conflicts myself?

**Comment by lpugin** [comment]
Yes, this is the problem. If you never touched them they should not appear in the PR. I can look at the conflicts in the files other than view_mensural.cpp, and you can look at this one. OK?

**Comment by donbyrd** [comment]
It's a deal :-) . I was wondering why GitHub even mentioned the hundreds of files I hadn't changed!

**Comment by lpugin** [comment]
I think it is better if I actually comment your changes in this branch and then I make the merge into rism-ch.

**Comment by donbyrd** [comment]
You say "I think it is better if I actually comment your changes in this branch and then I make the merge into rism-ch." Better than what? Does that mean I shouldn't have re-opened this PR?

**Comment by lpugin** [comment]
Better than merging in the other direction (from rism-ch into chmtl)

**Comment by donbyrd** [comment]
Ah. Yes, merging from chmtl into rism-ch definitely seems better than the other direction.

**Comment by lpugin** [comment]
Ok, then what I would suggest is you add the style_chtml.h and the draw_mensural_chtml.cpp files with your latest modifications and then I can do the merge. OK?

**Comment by donbyrd** [comment]
OK.

**Comment by donbyrd** [comment]
I've added style_chtml.h and draw_mensural_chtml.cpp to CHMTL/develop-mensural; at the moment they're identical to my style.h and draw_mensural.cpp. So, when you do the merge, I assume you'll ignore my style.h and draw_mensural.cpp. Now, after you've merged into rism-ch/develop-mensural, I'll want to get your changes into CHMTL/develop-mensural first, and from there into develop-chmtl, and then I guess I'll edit the make file to use style_chtml.h and draw_mensural_chtml.cpp instead of the regular files. Right? The only make file I see is tools/CMakeLists.txt, which I believe we run through Cmake to get a regular make file for the regular make utility. Is that right? But I don't see anything in CMakeLists.txt that looks like I could change it to do what I want! ??

I hope we can take care of this tomorrow (Tuesday); I'd like to give Giuliano something to show at the MEI conference (which I won't be attending).

**Comment by lpugin** [comment]
Yes, you should not have to change anything in the make file for the *.cpp file to be taken into account. You should only remove all the files generated by Cmake are run it again.

For the header file I have added one single define in style.h, which will not look for a `custom_style.h` if CUSTOM_VEROVIO_STYLE is define and use the style.h content otherwise. 
https://github.com/rism-ch/verovio/commit/3192157e50165bf80575bc85f484bee08484cf88

This should work for you but can also be useful to others. So you need to change style_chtml.h to custom_style.h, sorry about it.

**Comment by donbyrd** [comment]
I'm sorry for the slow response, after pushing for resolving things today! I understand about the make file, and I've renamed style_chtml.h to custom_style.h and pushed that change.

**Comment by donbyrd** [comment]
Based on our discussion in another thread this morning, it seems to me I should clean up the current mess by closing this pull request and posting one going the other way, merging from rism-ch:develop-mensural into CHMTL:develop-mensural; then do whatever is necessary to be sure CHMTL:develop-mensural has the appropriate changes from my work (I think CHMTL:develop-mensural-chmtl has all of i, but at this point I'm not sure of anything!); and finally open a new pull request like this one, i.e., from CHMTL:develop-mensural into rism-ch:develop-mensural. Does that sound right?

**Comment by lpugin** [comment]
I think we a closer to a solution than this. The branch CHMTL:develop-mensural-chmtl is actually already a merge of CHMTL:develop-mensural into rism-ch:develop-mensural. The only problem remaining is view_mensural_chmtl.cpp not compiling because it calls methods that are no longer there or that have changed. For example, DrawLedgerLines is no longer necessary because ledger lines are handled at the staff level. This is where comparing with view_mensural.cpp should be helpful to fix these remaining errors. So you can make the required changes in CHMTL:develop-mensural but please only in the view_mensural_chmtl.cpp file. Is this OK?

**Comment by lpugin** [comment]
We can indeed close it

**Comment by donbyrd** [comment]
Yes, that's OK.

**Comment by donbyrd** [comment]
An update: I successfully merged everything in my working copy, and made enough improvements to make Giuliano happy for now, e.g., @loc now works for mensural notes, though not rests. This required changing several other files as well as view_mensural.cpp. But with the MEI conference about to start (or maybe it has already?), I've spent all my time on that, none on maintaining the repository, and I'm leaving town for a week today. I'll work on getting everything committed and pushed when I get back.

**Comment by lpugin** [comment]
Thanks for the update. Did you push it somewhere? I would be interested to see the changes you had to do in the other files

**Comment by donbyrd** [comment]
No, I didn't push the changes anywhere. You asked me to "make the required changes in CHMTL:develop-mensural but please only in the view_mensural_chmtl.cpp file", which I makes sense. I guess CHMTL:develop-mensural-chmtl is the place to put them, and I'll do that in the next day or two.

**Comment by lpugin** [comment]
Sorry, I meant in CHMTL:develop-mensural-chmtl  where I would prefer you to make changes only to  view_mensural_chmtl.cpp. You can still make all the changes you need / want in CHMTL:develop-mensural which I am not going to merge.

**Comment by donbyrd** [comment]
I'm still (or again) confused. I thought we'd agreed that we'd use develop-mensural in CHMTL and rish-ch to keep in sync, i.e., to merge. No?

**Comment by lpugin** [comment]
Yes indeed, this was the original idea. But since you have started to make developments in chmtl:develop-mensural it cannot serve as a synchronisation branch anymore, and this is why I created chmtl:develop-mensural-chmtl for this.

**Pull request closed without merging**
